name: bam_dojo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  video_player: ^2.4.2
  widget_mask: ^1.0.0+0
  sensors_plus: ^1.3.2
  flutter_svg: ^1.1.1+1
  vector_math: ^2.1.2
  fast_immutable_collections: ^7.4.1

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/videos/
    - assets/page_color_transition/icons/
